[package]
name = "skeet"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Skeet tool for Bluesky"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bisky = "0.2.1"
chrono = "0.4.26"
url = "2.3.1"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
grep-cli = "0.1.7"
